// Types
export default Object.freeze({
    INITIALIZE:             'INITIALIZE',
    START_FETCHING_AUTH:    'START_FETCHING_AUTH',
    STOP_FETCHING_AUTH:     'STOP_FETCHING_AUTH',
    START_FETCHING_FEED:    'START_FETCHING_FEED',
    STOP_FETCHING_FEED:     'STOP_FETCHING_FEED',
    START_FETCHING_PROFILE: 'START_FETCHING_PROFILE',
    STOP_FETCHING_PROFILE:  'STOP_FETCHING_PROFILE',
    START_FETCHING_AVATAR:  'START_FETCHING_AVATAR',
    STOP_FETCHING_AVATAR:   'STOP_FETCHING_AVATAR',
    START_PROFILE_EDITING:  'START_PROFILE_EDITING',
    STOP_PROFILE_EDITING:   'STOP_PROFILE_EDITING',
    START_PASSWORD_EDITING: 'START_PASSWORD_EDITING',
    STOP_PASSWORD_EDITING:  'STOP_PASSWORD_EDITING'
});
