export default Object.freeze({
    FETCH_MOVIE_DETAILS:         'FETCH_MOVIE_DETAILS:',
    FETCH_MOVIE_DETAILS_SUCCESS: 'FETCH_MOVIE_DETAILS_SUCCESS',
    FETCH_MOVIE_DETAILS_FAIL:    'FETCH_MOVIE_DETAILS_FAIL',
    CLEAR_MOVIE_DETAILS:         'CLEAR_MOVIE_DETAILS'
});
