// Types
export default Object.freeze({
    FETCH_POSTS:         'FETCH_POSTS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAIL:    'FETCH_POSTS_FAIL',
    CREATE_POST:         'CREATE_POST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAIL:    'CREATE_POST_FAIL',
    DELETE_POST:         'DELETE_POST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL:    'DELETE_POST_FAIL',
    LIKE_POST:           'LIKE_POST',
    LIKE_POST_SUCCESS:   'LIKE_POST_SUCCESS',
    LIKE_POST_FAIL:      'LIKE_POST_FAIL'
});
