export default Object.freeze({
    FETCH_TOP_MOVIES:         'FETCH_TOP_MOVIES',
    FETCH_TOP_MOVIES_SUCCESS: 'FETCH_TOP_MOVIES_SUCCESS',
    FETCH_TOP_MOVIES_FAIL:    'FETCH_TOP_MOVIES_FAIL',
    ADD_TO_FAVORITES:         'ADD_TO_FAVORITES',
    ADD_TO_FAVORITES_SUCCESS: 'ADD_TO_FAVORITES_SUCCESS',
    ADD_TO_FAVORITES_FAIL:    'ADD_TO_FAVORITES_FAIL',
    GET_FAVORITES:            'GET_FAVORITES',
    GET_FAVORITES_SUCCESS:    'GET_FAVORITES_SUCCESS',
    GET_FAVORITES_FAIL:       'GET_FAVORITES_FAIL',
    DELETE_FAVORITE:          'DELETE_FAVORITE',
    DELETE_FAVORITE_SUCCESS:  'DELETE_FAVORITE_SUCCESS',
    DELETE_FAVORITE_FAIL:     'DELETE_FAVORITE_FAIL',
    FETCH_GENRES:             'FETCH_GENRES',
    FETCH_GENRES_SUCCESS:     'FETCH_GENRES_SUCCESS',
    FETCH_GENRES_FAIL:        'FETCH_GENRES_FAIL'
});
